// These styles apply to every route in the application
import { Montserrat } from 'next/font/google';
import './globals.css';
 
export const metadata = {
  title: 'AniToons - Anime and Manga',
  description: 'Generated by create next app',
};

const montserrat = Montserrat({
  subsets: ['latin'],
})
 
export default function RootLayout({children}:{children: React.ReactNode,}) {
  return (
    <html lang='en' className={montserrat.className}>
      <body>{children}</body>
    </html>
  );
}